[package]
name = "softql"
version.workspace = true
edition.workspace = true

[dependencies]
pest = "2.5"
pest_derive = "2.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lints]
workspace = true
