[package]
name = "text2softql"
version.workspace = true
edition.workspace = true

[dependencies]
reqwest = { version = "0.12.5", default-features = false, features = [
    "blocking",
    "json",
    "rustls-tls",
] }
serde = "1"
thiserror = "1"

[lints]
workspace = true
